### PR TITLE
feat(configuration): support npm scripts run configuration

### PR DESCRIPTION
**Pull request by BlackHole1**
Feature Demo:

https://user-images.githubusercontent.com/8198408/132616439-35cdbced-5199-4a50-a7fa-c441e6e4210e.mp4

### CODE REVIEW

**Comment by eirikb** [comment]
Thanks, but I'm having some problems running it. Do you see something wrong here?
image

The output is from pressing the arrow / ctrl + shift + alt + a

**Comment by BlackHole1** [comment]
Strangely enough, I didn't reproduce the problem.

https://user-images.githubusercontent.com/8198408/132804045-80eb0137-0c68-4e39-93d3-7d25f18db7db.mp4

From the screenshot, it looks like there is a problem with the state change?
Because on your screenshot `command model` does not seem to be disable

**Comment by eirikb** [comment]
Strange. If it works for you it's probably fine, and it doesn't seem to break anything else. Thanks :)

**Comment by eirikb** [comment]
I've published it now. Hope it will pass their checks. Last time I got an e-mail (manual, not automatic) where they complained about the to-version 999. Might have to fix that first, we'll se :smile:

**Comment by BlackHole1** [comment]
😂

**Pull request merged**
