### PR TITLE
feat: support string template in ava test title

### PR DESCRIPTION
**Pull request by BlackHole1**
support string template.

e.g:

```ts
const namespace = "[utils][utils-ajv]";

test(`${namespace} - test format`, () => { /*  ... */ }); // => `-m "* - test format"`
test(`${namespace} - test uuidv4`, () => { /*  ... */ }); // => `-m "* - test uuidv4"`
```

### CODE REVIEW

**Comment by BlackHole1** [comment]
@eirikb I would like to ask when are you going to update it on IDEA?

**Comment by eirikb** [comment]
Hi

I tried yesterday but there is something wrong about my release flow.
Previously I have manually changed the version, but I think that is suppose to be handled by the release action.
I have asked on Slack, but no reply yet.

If you know that would be great. According to this: https://github.com/JetBrains/intellij-platform-plugin-template#release-flow it seems I only need to specify version and all should be well. But it fails with version already existing (it does not upload with new version number)

**Comment by BlackHole1** [comment]
@eirikb I think I know the problem, I will submit a PR later to fix this

**Comment by eirikb** [comment]
The problem is that the version isn't automatically updated. Before I have done this afterwards by manually bumping it directly in `main`.  
After talking on Slack it seems this is good as anything else.   
I will do this later today, and release a new version.

**Comment by BlackHole1** [comment]
I thought for a while, this operation should be more appropriate for you to do.

You need to modify the `pluginVersion` in _gradle.properties_

Set it to `1.3.8` or `1.3.9` and submit a commit and then trigger the release action, there should be no problem

> If you are setting 1.3.8, then you need to remove 1.3.8 `tag` and `release` from github first.

**Comment by eirikb** [comment]
Yes, this is what I have done before. But I always expected the release flow to handle this for me.
It seems odd to do it manually, especially when PRs like yours isn't something I control, so the version should not be part of it :shrug:

**Comment by BlackHole1** [comment]
Because when you are ready to publish, action will run [./gradlew publishPlugin](https://github.com/eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator/blob/main/.github/workflows/release.yml#L33)

And `publishPlugin`'s will perform the following operation:

source code: [publishPlugin](https://github.com/eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator/blob/main/build.gradle.kts#L106-L112)
```kt
dependsOn("patchChangelog")
token.set(System.getenv("PUBLISH_TOKEN"))
// pluginVersion is based on the SemVer (https://semver.org) and supports pre-release labels, like 2.1.7-alpha.3
// Specify pre-release label to publish the plugin in a custom Release Channel automatically. Read more:
// https://plugins.jetbrains.com/docs/intellij/deployment.html#specifying-a-release-channel
channels.set(listOf(properties("pluginVersion").split('-').getOrElse(1) { "default" }.split('.').first()))
```

You can see that it will go and read the `pluginVersion` value in _gradle.properties_ , because you didn't change this value, the release script thought you were releasing 1.3.7 instead of 1.3.8.

----

On a code level, we can indeed do automatic version changes and releases, but I don't recommend it, and I think JetBrains feels the same way.

Because:

1. Version changes are more flexible and should not be left to automated programs
2. One advantage of the manual approach is that you have the flexibility to choose whether it is: `1.0.0` or `1.0.0-alpha.1`.
3. If the program was allowed to do this automatically, it would become very silly because it would only know to add one to `patch`
4. Whether it's a front-end project or a project in another language, you'll find that modifying the versioning bit is basically done manually.

**Comment by eirikb** [comment]
I don't expect selecting the version to be automatic, I expect it to use the version I manually put in Title of release and/or the tag

**Comment by BlackHole1** [comment]
I see what you mean, you're thinking: when I'm ready to publish, the program should automatically read the tag name as the version number, right?

**Comment by eirikb** [comment]
After every build, including your PR, I get a draft release. If I want to publish this I open the release, give it a title, a description and publish it. 
This is how the template is set up to work. The description becomes changelog, this is pushed back into the repo.
The version is whatever I give it as Title. The tag thing I think is new, at least I haven't seen it before when publishing before. At least not the dropdown + option to create a new one on-fly.

What it doesn't do, is change the version before publishing to JetBrains.
It will git push changelog back, but not version.

I have similar setups other places, which will `build` > `update version` > `push back to repo` > `publish to registry`.
Ref https://github.com/eirikb/domdom/blob/master/.github/workflows/release.yml#L42 . 
I think the draft-release flow is neater, if only it could bump the version.

**Comment by BlackHole1** [comment]
Okay, please give me ten minutes and I will submit a new PR to help you solve this problem

**Pull request merged**
